name: Deploy to OpenShift

env:
    IMAGE_REGISTRY: quay.io
    IMAGE_REGISTRY_USER: ${{ secrets.QUAY_LOGIN }}
    IMAGE_REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

    MICROSERVICENAME: games-microservice-py

    PORT: "5000"

    APP_NAME: ApiEndPointProject
    URL: "quay.io/536673/games-microservice-py:$GITHUB_SHA"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install OpenShift CLI
        run: |
          curl -Lo oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvzf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Log in to OpenShift
        run: |
          echo "sha256~KkKm1fDFqRMDz1TCRjtKX_A3IyLzVMEn-PLaynsGxzg" | oc login --token=$(cat) --server="${{ secrets.OPENSHIFT_SERVER }}"

      - name: Log in to Quay
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_LOGIN }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build Docker image
        run: |
          docker build -t ${{ env.URL}} .

      - name: Push Docker image
        run: |
          docker push ${{ env.URL}}

      - name: Check if deployment exists and create if missing
        run: |
          if ! oc get deployment ${{ env.MICROSERVICENAME }}; then
            echo "Deployment not found. Creating deployment..."
            oc create deployment ${{ env.MICROSERVICENAME }} --image=${{ env.URL}}
          else
            echo "Deployment exists."
          fi

          if ! oc get service ${{ env.MICROSERVICENAME }}; then
            echo "Service not found. Exposing deployment..."
            oc expose deployment ${{ env.MICROSERVICENAME }} --port=${{ env.PORT }}
          else
            echo "Service already exists."
          fi

      - name: Set environment variable for the deployment using the secret
        run: |
          oc set env deployment/${{ env.MICROSERVICENAME }} AZURE_TABLE_CONNECTION_STRING='$(oc get secret azure-connection-secret -o jsonpath="{.data.AZURE_TABLE_CONNECTION_STRING}" | base64 --decode)'

      - name: Update image in the deployment
        run: |
          oc set image deployment/${{ env.MICROSERVICENAME }} ${{ env.MICROSERVICENAME }}=${{ env.URL }}

      - name: Wait for deployment rollout to finish
        run: |
          for i in {1..3}; do
            oc rollout status deployment/${{ env.MICROSERVICENAME }}&& break || sleep 30
          done
